import type { Metadata } from "next";
import "../globals.css";
import { Nunito } from "next/font/google";
import { Header } from "@/shared/Header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next pizza",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      {" "}
      <Suspense>
        <Header />
      </Suspense>
      {children}
      {modal}
    </main>
  );
}
