export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="">{children}</main>;
}
