import { Container } from "@/shared/Container";
import { Header } from "@/shared/Header";
import { Suspense } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Suspense>
        <Header hasSearch={false} className="border-gray-200" />
      </Suspense>
      <Container>{children}</Container>
    </main>
  );
}
